# Generated by Django 4.0.4 on 2022-06-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blackbelt_holders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bth_reg', models.CharField(max_length=25)),
                ('bth_name', models.CharField(max_length=25)),
                ('bth_desig', models.CharField(max_length=20)),
                ('bth_image', models.ImageField(null=True, upload_to='image/blackbeltholder')),
            ],
        ),
    ]
