# Generated by Django 4.0.4 on 2022-06-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hbgimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bth_image', models.ImageField(null=True, upload_to='image/bgimg')),
            ],
        ),
    ]
