# Generated by Django 4.0.4 on 2022-06-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0002_hbgimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hbgimg',
            old_name='bth_image',
            new_name='bg_image',
        ),
    ]
