# Generated by Django 4.0.4 on 2022-06-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0003_rename_bth_image_hbgimg_bg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagefolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=25)),
            ],
        ),
    ]
