# Generated by Django 4.0.4 on 2022-06-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0005_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_name', models.FileField(null=True, upload_to='file')),
            ],
        ),
    ]
