# Generated by Django 4.0.4 on 2022-06-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0006_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='affiliation_name',
            field=models.ImageField(null=True, upload_to='file'),
        ),
    ]
