# Generated by Django 4.0.4 on 2022-06-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0007_alter_affiliation_affiliation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.ImageField(null=True, upload_to='video')),
            ],
        ),
    ]
