# Generated by Django 4.0.4 on 2022-06-09 19:08

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0008_videos'),
    ]

