# Generated by Django 4.0.3 on 2022-06-11 17:45

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0008_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.AddField(
            model_name='affiliation',
            name='affiliation_img',
            field=models.ImageField(null=True, upload_to='file'),
        ),
    ]
